export const defaultModes = [
  {
    name: 'standartMode',
    primaryColor: '#3D99F5',
    secondaryColor: '#21364A',
    textColor: '#E5E8EB',
    secondaryTextColor: '#8FADCC',
    bgColor: '#0F1A24',
    scheduledCallMode: true,
    stickers: false,
    restrictedSmileMode: true,
  },
  {
    name: 'workMode',
    primaryColor: '#3D99F5',
    secondaryColor: '#21364A',
    textColor: '#E5E8EB',
    secondaryTextColor: '#8FADCC',
    bgColor: '#0F1A24',
    scheduledCallMode: false,
    stickers: true,
    restrictedSmileMode: true,
  },
  {
    name: 'familyMode',
    primaryColor: '#FAD938',
    secondaryColor: '#F5F2E5',
    textColor: '#1C1A0D',
    secondaryTextColor: '#9E8F47',
    bgColor: '#FFFFFF',
    scheduledCallMode: false,
    stickers: true,
    restrictedSmileMode: true,
  },
];
